<a href="https://colab.research.google.com/github/jen0707/PythonDataA/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# numpy 불러와서 np로 사용
import numpy as np

In [ ]:
# 간단한 1차원 넘파이 배열 생성하고 출력
print(np.array([1, 2, 3]))

[1 2 3]


In [ ]:
# 별칭을 붙이지 않고 numpy 불러와서 사용
import numpy

print(np.array([1, 2, 3]))

[1 2 3]


In [ ]:
import numpy as np

arr_1 = np.array([1,2,3,4,5]) # 1차원 파이썬 리스트를 넘파이 배열로 변환
print(arr_1) # 넘파이 배열 출력

[1 2 3 4 5]


In [ ]:
# 파이썬 리스트에 *2 연산을 하면 같은 리스트를 2개 이어붙여진 결과 출력
list = [1, 2, 3]
print(list*2)

[1, 2, 3, 1, 2, 3]


In [ ]:
# 넘파이 1차원 배열인 arr_1 변수에 *2 연산을 하면 각 요소에 2를 곱한 결과 출력
import numpy as np
arr_1 = np.array([1, 2, 3])
print(arr_1 *2)

[2 4 6]


In [ ]:
import numpy as np

arr_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
# 2차원 파이썬 리스트를 ndarray로 변환

print(arr_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np

arr_3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13, 14, 15],[16,17,18]]])
# 3차원 파이썬 리스트를 넘파이 배열로 변환

print(arr_3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [ ]:
# 2차원 배열을 만든 후 axis 별 계산
import numpy as np

# 2D 배열 생성 (3행 4열)
arr = np.array([[1, 2, 3, 4,],[5, 6, 7,8],[9, 10, 11, 12]])

print("원본 배열: \n", arr)

원본 배열: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# axis=0 계산(열 기준, 세로방향 연산))
sum_axis0 = np.sum(arr, axis=0)
print("axis=0(세로 방향) 합계: \n",sum_axis0)

axis=0(세로 방향) 합계: 
 [15 18 21 24]


In [ ]:
# axis=1 계산(행 기준, 가로방향 연산)
sum_axis1 = np.sum(arr, axis =1)
print("axis=1(가로 방향) 합계: \n", sum_axis1)

axis=1(가로 방향) 합계: 
 [10 26 42]


In [ ]:
# 3차원 배열 생성
arr_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print("원본 3D 배열: \n", arr_3d)

원본 3D 배열: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# axis=0 기준 계산
sum_3d_axis0 = np.sum(arr_3d, axis=0)
print("axis=0 (깊이 기준 합계): \n", sum_3d_axis0)

axis=0 (깊이 기준 합계): 
 [[ 8 10 12]
 [14 16 18]]


In [ ]:
# axis=1 기준 계산
sum_3d_axis1 = np.sum(arr_3d, axis=1)
print("axis=1 (행 기준 합계): \n", sum_3d_axis1)

axis=1 (행 기준 합계): 
 [[ 5  7  9]
 [17 19 21]]


In [ ]:
# axis=2 기준 계산
sum_3d_axis2 = np.sum(arr_3d, axis=2)
print("axis=2 (열 기준 합계): \n", sum_3d_axis2)

axis=2 (열 기준 합계): 
 [[ 6 15]
 [24 33]]


In [ ]:
# 넘파이 배열을 하나 만들어 변수에 넣고 .dtype을 입력한 결과 출력
import numpy as np
arr = np.array([1,2,3])
print(arr.dtype)

int64


In [ ]:
import numpy as np
arr = np.array([1,2,3])
print(arr.dtype)
# dtype 속성을 사용하여 배열의 데이터 타입 출력

int64


In [ ]:
# array( ) 함수의 dtype 매개변수에 데이터 타입을 인수로 입력하여 데이터 타입 지정
print(np.array([1,2,3], dtype="int8").dtype)

int8


In [ ]:
# dtype 매개변수에 데이터 타입 코드를 인수로 입력하여 데이터 타입 지정
print(np.array([1,2,3], dtype="i4").dtype)

int32


In [ ]:
# 넘파이 배열과 파이썬 리스트 선언
import numpy as np

# 넘파이 배열
ndarray_1 = np.array([1, 2, 3])
ndarray_2 = np.array([4, 5, 6])

# 파이썬 리스트
list_1 = [1, 2, 3]
list_2 = [4, 5, 6]

In [ ]:
# 넘파이 배열은 두 배열의 요소를 일대일 대응하여 더함, 이것을 요소별 연산이라 함.
# 요소별 연산 : 두 배열이 동일한 크기를 가질 때, 각 요소끼리 1:1로 연산이 수행되는 것을 의미
print(ndarray_1+ndarray_2)

# 파이썬 리스트는 두 리스트를 연결함
print(list_1+list_2)

[5 7 9]
[1, 2, 3, 4, 5, 6]


In [ ]:
# 파이썬 리스트로 넘파이 배열 생성하기
import numpy as np

# 넘파이 정수형 배열 생성
int_arr = np.array([2, 3, 4])
print(int_arr) # 넘파이 배열 출력
print(int_arr.dtype) # 넘파이 배열의 데이터 타입 출력

# 넘파이 실수형 배열 생성
float_arr = np.array([2.1, 3.2, 4.3])
print(float_arr)
print(float_arr.dtype)

[2 3 4]
int64
[2.1 3.2 4.3]
float64


In [ ]:
# 파이썬 튜플로 넘파이 문자열 배열 생성하기
tuple_arr = np.array(["i","j","k"])
# 데이터 타입 확인
print(tuple_arr.dtype)

<U1


In [ ]:
# 파이썬 튜플에 불리언 데이터를 담아 넘파이 논리형 배열 생성하기
tuple_bool_arr = np.array([True,False])
print(tuple_bool_arr.dtype)

bool


In [ ]:
# dtype 매개변수로 넘파이 배열의 문자열 길이 지정하기
dtype_arr = np.array(["ab","cd","e"], dtype="<U2")
print(dtype_arr)
print(dtype_arr.dtype)

['ab' 'cd' 'e']
<U2


In [ ]:
import numpy as np

# a 라는 변수에 (3, 4) 크기의 넘파이 2차원 배열 생성
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# 배열의 차원과 차원의 크기 반환
print(a.shape)

# 배열의 차원 수 반환
print(a.ndim)

# 배열의 데이터 타입 반환
print(a.dtype)

# 배열의 각 요소의 크기를 바이트 단위로 반환
print(a.itemsize)

# 배열의 총 요소의 수 반환
print(a.size)


(3, 4)
2
int64
8
12


In [ ]:
# np.zeros( ) 함수를 사용해 모든 요소가 0으로 초기화된 배열 생성
import numpy as np

# (3, 4) 크기의 배열을 생성하여 0으로 채움
print(np.zeros((3,4)))

# (3, 4) 크기의 배열을 데이터 타입을 정수로 생성한 후, 0으로 채움
print(np.zeros((3,4), dtype = int))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
# (2, 3, 4) 크기의 배열을 생성하여 데이터 타입을 정수로 설정한 후, 1로 채움
print(np.ones((2, 3, 4), dtype=int))

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [ ]:
# (2, 3) 크기의 빈 배열 생성
print(np.empty((2,3)))

[[3.37336328e-316 0.00000000e+000 6.77642281e-310]
 [6.77642281e-310 0.00000000e+000 0.00000000e+000]]


In [ ]:
# arange( ) 함수로 넘파이 배열 만들기
import numpy as np

# 10 이상 30 미만까지 5 간격으로 생성
print(np.arange(10, 30, 5))

# 0 이상 2 미만까지 0.3 간격으로 생성
print(np.arange(0, 2, 0.3))


[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [ ]:
# linspace( ) 함수로 넘파이 배열 만들기
# 1 이상 10 이하까지 값을 가진 크기 10짜리 배열 생성
print(np.linspace(1, 10, 10))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
# 요소별 연산으로 사칙 연산하기
import numpy as np

# a와 b 배열 생성하여 출력
a = np.array([10, 20, 30, 40])
b = np.arange(1, 5)
print(a)
print(b)

# 덧셈 연산
print(a+b)

# 뺄셈 연산
print(a-b)

# 곱셈 연산
print(a*b)

# 나눗셈 연산
print(a/b)


[10 20 30 40]
[1 2 3 4]
[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


In [ ]:
# 요소별 연산으로 행렬 곱셈하기
# A와 B 배열 생성
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])

# A * B : 요소별 곱셈 연산
print(A*B)

# A @ B : 행렬 곱셈 사용
print(A@B)


[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


In [ ]:
# 요소별 연산으로 비교 연산하기
import numpy as np

# A와 B 배열 생성
A = np.array([1, 2, 3, 4])
B = np.array([1, 1, 3, 3])

# 비교 연산
print(A>B)
print(A==B)

[False  True False  True]
[ True False  True False]


In [ ]:
# 수학 함수와 함께 벡터화 연산해보기
import numpy as np

# A 배열 생성
A = np.array([4, 16, 25])

# 제곱근 함수
print(np.sqrt(A))

[2. 4. 5.]


In [ ]:
import numpy as np
# a 배열 생성 & 출력
# 0부터 8 미만까지 출력하고 (2, 4) 크기로 재가공하고 제곱하여 출력
a = np.arange(8).reshape(2, 4) ** 2
print(a)

# 모든 요소의 합
print(a.sum())

# 모든 요소 중 평균
print(a.mean())

# 모든 요소 중 최솟값
print(a.min())

# 모든 요소 중 최댓값
print(a.max())

# 모든 요소의 누적합
print(a.cumsum())

# 모든 요소 중 최댓값의 인덱스
print(a.argmax())

[[ 0  1  4  9]
 [16 25 36 49]]
140
17.5
0
49
[  0   1   5  14  30  55  91 140]
7


In [ ]:
# 집계 함수에 축 사용해보기
import numpy as np

# 0부터 8미만까지 출력하고 (2, 4) 크기로 재가공하고 제곱하여 출력
a = np.arange(8).reshape(2, 4) ** 2
print(a)

# axis = 0은 열 기준으로 연산
a_axis0 = np.sum(a, axis=0)
print(a_axis0)

# axis = 1은 행 기준으로 연산
a_axis1 = np.sum(a, axis=1)
print(a_axis1)

[[ 0  1  4  9]
 [16 25 36 49]]
[16 26 40 58]
[ 14 126]


In [ ]:
# 넘파이 1차원 배열의 특정 위치의 값을 가져오는 단일 요소 인덱싱
import numpy as np

a = np.array([0, 1, 2, 3, 4, 5])
print(a)

# 인덱스가 0인, 인덱스가 3인 요소 출력
print(a[0])
print(a[3])

[0 1 2 3 4 5]
0
3


In [ ]:
# 2차원 배열의 특정 위치를 선택
b = np.array([[0, 1, 2], [3, 4, 5]])
print(b)

# 인덱스가 [1, 0]인, 인덱스가 [1, 2]인 요소 출력
print(b[1,0])
print(b[1,2])

[[0 1 2]
 [3 4 5]]
3
5


In [ ]:
import numpy as np

a = np.array([0, 1, 2, 3, 4, 5])
print(a)

# 인덱스 0 이상 인덱스 3 미만 범위의 요소 출력
print(a[0:3])

[0 1 2 3 4 5]
[0 1 2]


In [ ]:
# 2차원 배열에서 4보다 큰 값에 일대일 대응하는 논리형 배열 생성
import numpy as np

a = np.arange(12).reshape(3, 4)
print(a)

# a > 4 조건을 적용한 논리형 배열 생성
b = a > 4
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [ ]:
# 논리형 배열 b를 사용하여 조건에 맞는 요소 추출
print(a[b])

# 추출한 요소들의 배열 모양
print(a[b].shape)

[ 5  6  7  8  9 10 11]
(7,)


In [ ]:
# 논리형 배열인 b를 이용하여 원본 a 배열의 값 변경하기(True인 값의 위치에 변경하기)
a[b] = 1000
print(a)

[[   0    1    2    3]
 [   4 1000 1000 1000]
 [1000 1000 1000 1000]]


In [ ]:
# 정수 배열 인덱싱 이해하기
import numpy as np

a = np.array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])
i = np.array([1,1,3,4])

# 배열 a에서 배열 i에 지정된 인덱스의 원소들을 출력
print(a[i])

# 배열 a에서 배열 j에 지정된 인덱스의 원소들을 출력
j = np.array([[3, 4], [5, 6]])
print(a[j])

['b' 'b' 'd' 'e']
[['d' 'e']
 ['f' 'g']]


In [ ]:
b = np.array(['a', 'b', 'c', 'd'])
k = np.array([3, 2, 1, 0])

# 배열 b에서 배열 k에 지정된 인덱스의 원소들을 재배열
b = b[k]
print(b)

['d' 'c' 'b' 'a']


In [ ]:
# reshape( ) 함수로 (3, 4) 형태의 배열 생성
import numpy as np
a = np.arange(12).reshape(3, 4)

# a 배열 생성
a = np.arange(12).reshape(3,4)
print(a)
print(a.shape)
print(a.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
2


In [ ]:
# a 배열을 다시 reshape( ) 함수로 변형하여 b에 저장
# .reshape : 지정한 차원으로 변경하고 새로운 배열 반환
b = a.reshape(2,6)
print(b)
print(b.shape)

# 원본 a 배열은 기존의 (3, 4) 형태 유지
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
(2, 6)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# 1번째 매개변수에 -1을 전달해도 같은 결과가 나옴(자동 계산)
b = a.reshape(-1,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
import numpy as np

# .resize() : 지정한 차원으로 변경하고 원본 배열 자체를 변경
a = np.arange(12)
a.resize(4,3)
print(a)
print(a.shape)

# 따로 반환하는 값 없음
print(a.resize(4, 3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)
None


In [ ]:
# (3, 4) 형태의 배열을 1차원 배열로 평탄화
import numpy as np

a = np.arange(12).reshape(3, 4)

# .ravel : 1차원 배열로 크기 변경
print(a.ravel())

# .reshape(-1) : 1차원 배열로 크기 변경
print(a.reshape(-1))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
import numpy as np

A = np.arange(12).reshape(2, 6)
print(A)

# .T : [2, 6]을 [6, 2] 반환으로 전치(transpose) 변환
print(A.T)
print(A.T.shape)

# 만약 전치 형태로 원본 A 배열에 저장하고 싶다면, A배열에 A.T 값을 할당
A = A.T
print(A)
print(A.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]
(6, 2)
[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]
(6, 2)


In [ ]:
# 다차원 배열을 수직 및 수평으로 합치기
import numpy as np

# a 배열, b 배열 생성
a = np.array([1, 2, 3, 4]).reshape(2, 2)
b = np.array([5, 6, 7, 8]).reshape(2, 2)

# 수직으로 합치기
print(np.vstack((a,b)))

# 수평으로 합치기
print(np.hstack((a,b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# 다차원 배열을 수직 및 수평으로 분할하기
import numpy as np

# a 배열 생성
a = np.arange(12).reshape(2, 6)
print(a)

# 수직으로 분할하기
print(np.vsplit(a,2))

# 수평으로 분할하기
print(np.hsplit(a,3))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]])]
[array([[0, 1],
       [6, 7]]), array([[2, 3],
       [8, 9]]), array([[ 4,  5],
       [10, 11]])]
